name: enva
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  bloc: ^9.0.0
  drift: ^2.25.0
  equatable: ^2.0.7
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_facebook_auth: ^7.1.1
  flutter_secure_storage: ^9.2.4
  fluttertoast: ^8.2.11
  google_sign_in: ^6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  share_plus: ^10.1.4
  sqlite3_flutter_libs: ^0.5.30
  supabase_flutter: ^2.8.3
  shared_preferences: ^2.1.1
  google_fonts: ^6.1.0
  card_swiper: ^3.0.1
  # flutter_localizations: # add this
  #   sdk: flutter
  rive: ^0.13.20
  cached_network_image: ^3.4.1
  intl: ^0.18.0
  image_picker: ^1.0.4
  path: ^1.8.3
  provider: ^6.1.1
  cloudinary_flutter: ^1.0.0
  cloudinary_url_gen: ^1.0.0
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.4
  go_router: ^14.2.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  url_launcher: ^6.1.12
  googleapis_auth: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/fonts/
    - assets/
  fonts:
    - family: Aldrich
      fonts:
        - asset: assets/fonts/Aldrich-Regular.ttf
          weight: 400
