// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyYi9dXlTzUCtuP9cAKqDB4Mm3rbPuYsU',
    appId: '1:135461409715:web:327fe74abc5f57ab4e31c6',
    messagingSenderId: '135461409715',
    projectId: 'enva-88ec8',
    authDomain: 'enva-88ec8.firebaseapp.com',
    storageBucket: 'enva-88ec8.firebasestorage.app',
    measurementId: 'G-3T92CZQZ5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlJZ9UjFG8Zb26WD1wo1DVJ7Pc3OF4IPw',
    appId: '1:135461409715:android:c4649fe580f8ccab4e31c6',
    messagingSenderId: '135461409715',
    projectId: 'enva-88ec8',
    storageBucket: 'enva-88ec8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrwjhcv8Skryg0iR_PfWqfZlz9AUiAfJA',
    appId: '1:135461409715:ios:56529ff0fde9e0074e31c6',
    messagingSenderId: '135461409715',
    projectId: 'enva-88ec8',
    storageBucket: 'enva-88ec8.firebasestorage.app',
    iosBundleId: 'com.example.enva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrwjhcv8Skryg0iR_PfWqfZlz9AUiAfJA',
    appId: '1:135461409715:ios:56529ff0fde9e0074e31c6',
    messagingSenderId: '135461409715',
    projectId: 'enva-88ec8',
    storageBucket: 'enva-88ec8.firebasestorage.app',
    iosBundleId: 'com.example.enva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyYi9dXlTzUCtuP9cAKqDB4Mm3rbPuYsU',
    appId: '1:135461409715:web:821a93442757a3aa4e31c6',
    messagingSenderId: '135461409715',
    projectId: 'enva-88ec8',
    authDomain: 'enva-88ec8.firebaseapp.com',
    storageBucket: 'enva-88ec8.firebasestorage.app',
    measurementId: 'G-0CVVFCZMBF',
  );
}
